name: Build faucet docker image
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  git-sync:
    name: git-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: get git commit hash
        id: git_commit_hash
        shell: bash
        run: |
          echo "::set-output name=git-commit-hash::$(echo $(git log --pretty=format:'%h' -n 1))"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker-build-push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: parithoshj/testnet-faucet:${{ steps.git_commit_hash.outputs.git-commit-hash }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
